# Generated by Django 3.1.7 on 2021-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('female', 'FEMALE'), ('male', 'male')], max_length=15)),
                ('date_of_birth', models.DateTimeField(max_length=15)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('bvn', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('savings', 'SAVINGS'), ('current', 'CURRENT'), ('deposit', 'DEPOSIT'), ('dom', 'DOM')], max_length=15)),
                ('employment_status', models.CharField(choices=[('employed', 'EMPLOYED'), ('self employed', 'SELF EMPLOYED'), ('freelance', 'FREELANCE'), ('unemployed', 'UNEMPLOYED')], max_length=25)),
                ('employer', models.CharField(max_length=255)),
                ('employer_number', models.IntegerField()),
                ('employer_email', models.EmailField(max_length=60)),
                ('employer_address', models.CharField(max_length=255)),
                ('employer_location', models.CharField(max_length=255)),
                ('kin_first_name', models.CharField(max_length=255)),
                ('kin_last_name', models.CharField(max_length=255)),
                ('kin_phone', models.IntegerField()),
                ('kin_email', models.EmailField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
