# Generated by Django 3.1.7 on 2021-04-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('savings', 'SAVINGS'), ('current', 'CURRENT'), ('deposit', 'DEPOSIT'), ('dom', 'DOM')], default='savings', max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
