# Generated by Django 3.1.7 on 2021-02-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210222_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('account_type', models.CharField(choices=[('savings', 'SAVINGS'), ('curreent', 'CURRENT')], default='savings', max_length=8)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
