# Generated by Django 3.1.7 on 2021-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210411_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='employer_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
