# Generated by Django 3.1.7 on 2021-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_type',
            field=models.CharField(choices=[('savings', 'SAVINGS'), ('current', 'CURRENT')], default='savings', max_length=8),
        ),
    ]
