# Generated by Django 3.1.7 on 2021-02-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210223_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDetails',
        ),
    ]
