# Generated by Django 3.1.7 on 2021-04-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210411_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kin_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
