# Generated by Django 3.1.7 on 2021-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('account_type', models.CharField(choices=[('savings', 'SAVINGS'), ('current', 'CURRENT')], default='savings', max_length=8)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('dep_account', models.IntegerField(default=0)),
                ('dep_user_name', models.CharField(default=None, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'transaction_deposit',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(default=None, max_length=50)),
                ('receiver_account', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_amount', models.IntegerField()),
                ('withdraw_account', models.IntegerField()),
                ('withdraw_username', models.CharField(default=None, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
