# Generated by Django 3.1.7 on 2021-04-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='dep_user_name',
        ),
    ]
