# Generated by Django 3.1.7 on 2021-04-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_deposit_dep_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.ForeignKey(default=11, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.transfer')),
            ],
        ),
    ]
