# Generated by Django 3.1.7 on 2021-02-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_deposit_dep_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='dep_account',
            field=models.IntegerField(default=0),
        ),
    ]
