# Generated by Django 3.1.7 on 2021-04-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='email',
            new_name='dep_email',
        ),
    ]
