# Generated by Django 3.1.7 on 2021-02-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_deposit_dep_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='dep_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='deposit',
            name='dep_user_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
