# Generated by Django 3.1.7 on 2021-04-08 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20210408_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='amount',
            new_name='transaction',
        ),
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
