# Generated by Django 3.1.7 on 2021-02-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20210226_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='period',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='rate',
        ),
    ]
