# Generated by Django 3.1.7 on 2021-02-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(default=None, max_length=50)),
                ('receiver_account', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
