# Generated by Django 3.1.7 on 2021-04-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20210408_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
    ]
