# Generated by Django 3.1.7 on 2021-02-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20210226_1357'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deposit',
            table=None,
        ),
    ]
