# Generated by Django 3.1.7 on 2021-02-24 10:34

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 24, 10, 33, 48, 752174, tzinfo=utc), verbose_name='transaction date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='transaction date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='transaction date'),
            preserve_default=False,
        ),
    ]
