# Generated by Django 3.1.7 on 2021-02-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20210224_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
