# Generated by Django 3.1.7 on 2021-02-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_accountdetails_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='last_login',
        ),
        migrations.AddField(
            model_name='deposit',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
