# Generated by Django 3.1.7 on 2021-02-25 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20210225_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
