# Generated by Django 3.1.7 on 2021-02-25 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20210225_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
